site_name: ICAEW Digital Archive Handbook
site_url: https://example.com/
nav:
    - Home: index.md
    - 'User guides':
        - 'Why digital preservation and web-archiving?': 'user-guides/why-dp-web-archives.md'
        - 'Overview of the ICAEW Digital Archive': 'user-guides/overview.md'
        - 'Preservica':
            - 'Overview': 'user-guides/preservica/preservica-overview.md'
            - 'Accessing and searching Preservica': 'user-guides/preservica/accessing-preservica.md'
        - 'Web archives (via Preservica and Archive-It)':
            - 'Overview': 'user-guides/web-archiving/web-archive-overview.md'
            - 'Accessing and searching the web archives': 'user-guides/web-archiving/accessing-the-web-archives.md'
    - 'Admin guides':
        - 'Preservica':
            - 'Standard ingest workflow': 'admin-guides/preservica/standard-ingest-workflow.md'
            - 'Appraisal': 'admin-guides/preservica/appraisal.md'
            - 'Ingest workflow': 'admin-guides/preservica/ingest-workflow.md'
            - 'Post Ingest' : 'admin-guides/preservica/post-ingest.md'
            - 'Dublin Core': 'admin-guides/preservica/dublin-core.md'
            - 'Uploading large files via AWS CLI': 'admin-guides/preservica/aws-cli.md'
            - 'Filename conventions': 'admin-guides/preservica/filename-conventions.md'
            - 'Backing up Preservica locally': 'admin-guides/preservica/backing-up.md'
            - 'Downloading StreamAMG videos': 'admin-guides/preservica/downloading-streamamg-videos.md'
            - 'Downloading YouTube videos (YouTube Data API)': 'admin-guides/preservica/downloading-youtube-videos-api.md'
            - 'yt-dlp and youtube-dl': 'admin-guides/preservica/yt-dlp-youtube-dl.md'
            - 'Archived pages': 'admin-guides/preservica/archived-pages.md'
        - 'Web archives':
            - 'Web crawl process overview': 'admin-guides/web-archiving/crawl-process-overview.md'
            - 'Wget': 'admin-guides/web-archiving/wget.md'
            - 'Browsertrix-crawler': 'admin-guides/web-archiving/browsertrix.md'
            - 'Browsertrix custom behaviors': 'admin-guides/web-archiving/browsertrix-behaviors.md'
            - 'Monthly web captures': 'admin-guides/web-archiving/monthly-web-captures.md'
            - 'Appendix': 'admin-guides/web-archiving/appendix.md'
        - 'Digital archiving workstation setup': 'admin-guides/digital-archive-workstation.md'
        - 'Editing the ICAEW Digital Archive Handbook': 'admin-guides/editing-digital-archive-handbook.md'
        - 'Reporting / Statistics': 'admin-guides/reporting.md'
    - Useful resources: useful-resources.md
    - Logins: logins.md
use_directory_urls: false
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.tabs
plugins:
    - offline
    - search
extra_css:
  - assets/css/custom.css
